// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_ushelf_faceFace_Fa000_Ctr000 = polygon({ points: [ [ 20.0000, 60.0000 ],
	[ 680.0000, 60.0000 ],
	[ 680.0000, 420.0000 ],
	[ 20.0000, 420.0000 ],
	[ 20.0000, 60.0000 ] ] });

face_fig_ushelf_faceFace_Fa000 = ctr_face_fig_ushelf_faceFace_Fa000_Ctr000;
fig_ushelf_faceFace = face_fig_ushelf_faceFace_Fa000;
const ctr_face_fig_ushelf_faceSide_Fa000_Ctr000 = polygon({ points: [ [ 280.0000, 0.0000 ],
	[ 280.0000, 580.0000 ],
	[ 0.0000, 580.0000 ],
	[ 0.0000, 60.0000 ],
	[ 30.0000, 60.0000 ],
	[ 30.0000, 0.0000 ],
	[ 280.0000, 0.0000 ] ] });

face_fig_ushelf_faceSide_Fa000 = ctr_face_fig_ushelf_faceSide_Fa000_Ctr000;
fig_ushelf_faceSide = face_fig_ushelf_faceSide_Fa000;
const ctr_face_fig_ushelf_faceSideR_Fa000_Ctr000 = polygon({ points: [ [ 280.0000, 0.0000 ],
	[ 280.0000, 430.0000 ],
	[ 0.0000, 430.0000 ],
	[ 0.0000, 60.0000 ],
	[ 30.0000, 60.0000 ],
	[ 30.0000, 0.0000 ],
	[ 280.0000, 0.0000 ] ] });

face_fig_ushelf_faceSideR_Fa000 = ctr_face_fig_ushelf_faceSideR_Fa000_Ctr000;
fig_ushelf_faceSideR = face_fig_ushelf_faceSideR_Fa000;
const ctr_face_fig_ushelf_faceTop_Fa000_Ctr000 = polygon({ points: [ [ 20.0000, 20.0000 ],
	[ 680.0000, 20.0000 ],
	[ 680.0000, 280.0000 ],
	[ 20.0000, 280.0000 ],
	[ 20.0000, 20.0000 ] ] });

face_fig_ushelf_faceTop_Fa000 = ctr_face_fig_ushelf_faceTop_Fa000_Ctr000;
fig_ushelf_faceTop = face_fig_ushelf_faceTop_Fa000;
const ctr_face_fig_ushelf_faceBeamTop_Fa000_Ctr000 = polygon({ points: [ [ 20.0000, 20.0000 ],
	[ 50.0000, 20.0000 ],
	[ 50.0000, 170.0000 ],
	[ 20.0000, 170.0000 ],
	[ 20.0000, 20.0000 ] ] });

face_fig_ushelf_faceBeamTop_Fa000 = ctr_face_fig_ushelf_faceBeamTop_Fa000_Ctr000;
const ctr_face_fig_ushelf_faceBeamTop_Fa001_Ctr000 = polygon({ points: [ [ 650.0000, 20.0000 ],
	[ 680.0000, 20.0000 ],
	[ 680.0000, 170.0000 ],
	[ 650.0000, 170.0000 ],
	[ 650.0000, 20.0000 ] ] });

face_fig_ushelf_faceBeamTop_Fa001 = ctr_face_fig_ushelf_faceBeamTop_Fa001_Ctr000;
const ctr_face_fig_ushelf_faceBeamTop_Fa002_Ctr000 = polygon({ points: [ [ 50.0000, 20.0000 ],
	[ 650.0000, 20.0000 ],
	[ 650.0000, 50.0000 ],
	[ 50.0000, 50.0000 ],
	[ 50.0000, 20.0000 ] ] });

face_fig_ushelf_faceBeamTop_Fa002 = ctr_face_fig_ushelf_faceBeamTop_Fa002_Ctr000;
fig_ushelf_faceBeamTop = union( face_fig_ushelf_faceBeamTop_Fa000, face_fig_ushelf_faceBeamTop_Fa001, face_fig_ushelf_faceBeamTop_Fa002 );

const subpax_ushelf_plateau =
	translate( [ 0, 0, 200, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 20}, fig_ushelf_faceTop )
		)
	);


const subpax_ushelf_back =
	translate( [ 0, 20, 0, ],
		rotate( [ 1.5707963267948966, 0, 0, ],
			   extrudeLinear( {height: 20}, fig_ushelf_faceFace )
		)
	);


const subpax_ushelf_sideL =
	translate( [ 680, 0, 0, ],
		rotate( [ 1.5707963267948966, 0, 1.5707963267948966, ],
			   extrudeLinear( {height: 20}, fig_ushelf_faceSide )
		)
	);


const subpax_ushelf_sideR =
	translate( [ 0, 0, 0, ],
		rotate( [ 1.5707963267948966, 0, 1.5707963267948966, ],
			   extrudeLinear( {height: 20}, fig_ushelf_faceSideR )
		)
	);


const subpax_ushelf_beam =
	translate( [ 0, 0, 170, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 30}, fig_ushelf_faceBeamTop )
		)
	);

const pax_ushelf = union( subpax_ushelf_plateau, subpax_ushelf_back, subpax_ushelf_sideL, subpax_ushelf_sideR, subpax_ushelf_beam );

return pax_ushelf;
}
module.exports = { main };
