// Generated by Parametrix
ca_ushelf_faceFace_000 = [ [ 20.0000, 60.0000 ],[ 680.0000, 60.0000 ],[ 680.0000, 420.0000 ],[ 20.0000, 420.0000 ],[ 20.0000, 60.0000 ] ];
cb_ushelf_faceFace_000 = [  0, 1, 2, 3, 4 ];
a_ushelf_faceFace = concat(ca_ushelf_faceFace_000);
b_ushelf_faceFace = [cb_ushelf_faceFace_000];
ca_ushelf_faceSide_000 = [ [ 280.0000, 0.0000 ],[ 280.0000, 580.0000 ],[ 0.0000, 580.0000 ],[ 0.0000, 60.0000 ],[ 30.0000, 60.0000 ],[ 30.0000, 0.0000 ],[ 280.0000, 0.0000 ] ];
cb_ushelf_faceSide_000 = [  0, 1, 2, 3, 4, 5, 6 ];
a_ushelf_faceSide = concat(ca_ushelf_faceSide_000);
b_ushelf_faceSide = [cb_ushelf_faceSide_000];
ca_ushelf_faceSideR_000 = [ [ 280.0000, 0.0000 ],[ 280.0000, 430.0000 ],[ 0.0000, 430.0000 ],[ 0.0000, 60.0000 ],[ 30.0000, 60.0000 ],[ 30.0000, 0.0000 ],[ 280.0000, 0.0000 ] ];
cb_ushelf_faceSideR_000 = [  0, 1, 2, 3, 4, 5, 6 ];
a_ushelf_faceSideR = concat(ca_ushelf_faceSideR_000);
b_ushelf_faceSideR = [cb_ushelf_faceSideR_000];
ca_ushelf_faceTop_000 = [ [ 20.0000, 20.0000 ],[ 680.0000, 20.0000 ],[ 680.0000, 280.0000 ],[ 20.0000, 280.0000 ],[ 20.0000, 20.0000 ] ];
cb_ushelf_faceTop_000 = [  0, 1, 2, 3, 4 ];
a_ushelf_faceTop = concat(ca_ushelf_faceTop_000);
b_ushelf_faceTop = [cb_ushelf_faceTop_000];
ca_ushelf_faceBeamTop_000 = [ [ 20.0000, 20.0000 ],[ 50.0000, 20.0000 ],[ 50.0000, 170.0000 ],[ 20.0000, 170.0000 ],[ 20.0000, 20.0000 ] ];
cb_ushelf_faceBeamTop_000 = [  0, 1, 2, 3, 4 ];
ca_ushelf_faceBeamTop_001 = [ [ 650.0000, 20.0000 ],[ 680.0000, 20.0000 ],[ 680.0000, 170.0000 ],[ 650.0000, 170.0000 ],[ 650.0000, 20.0000 ] ];
cb_ushelf_faceBeamTop_001 = [  5, 6, 7, 8, 9 ];
ca_ushelf_faceBeamTop_002 = [ [ 50.0000, 20.0000 ],[ 650.0000, 20.0000 ],[ 650.0000, 50.0000 ],[ 50.0000, 50.0000 ],[ 50.0000, 20.0000 ] ];
cb_ushelf_faceBeamTop_002 = [  10, 11, 12, 13, 14 ];
a_ushelf_faceBeamTop = concat(ca_ushelf_faceBeamTop_000, ca_ushelf_faceBeamTop_001, ca_ushelf_faceBeamTop_002);
b_ushelf_faceBeamTop = [cb_ushelf_faceBeamTop_000, cb_ushelf_faceBeamTop_001, cb_ushelf_faceBeamTop_002];

module subpax_ushelf_plateau () {
	translate( [ 0, 0, 200 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 20) polygon(a_ushelf_faceTop, b_ushelf_faceTop);
}

module subpax_ushelf_back () {
	translate( [ 0, 20, 0 ])
		rotate( [ 90, 0, 0 ])
			   linear_extrude(height = 20) polygon(a_ushelf_faceFace, b_ushelf_faceFace);
}

module subpax_ushelf_sideL () {
	translate( [ 680, 0, 0 ])
		rotate( [ 90, 0, 90 ])
			   linear_extrude(height = 20) polygon(a_ushelf_faceSide, b_ushelf_faceSide);
}

module subpax_ushelf_sideR () {
	translate( [ 0, 0, 0 ])
		rotate( [ 90, 0, 90 ])
			   linear_extrude(height = 20) polygon(a_ushelf_faceSideR, b_ushelf_faceSideR);
}

module subpax_ushelf_beam () {
	translate( [ 0, 0, 170 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 30) polygon(a_ushelf_faceBeamTop, b_ushelf_faceBeamTop);
}

module pax_ushelf () {
	union () {
		subpax_ushelf_plateau();
subpax_ushelf_back();
subpax_ushelf_sideL();
subpax_ushelf_sideR();
subpax_ushelf_beam();
	}
}

pax_ushelf();
