// Generated by Parametrix
ca_bookshelf_faceFace_000 = [ [ 20.0000, 60.0000 ],[ 1180.0000, 60.0000 ],[ 1180.0000, 630.0000 ],[ 20.0000, 630.0000 ],[ 20.0000, 60.0000 ] ];
cb_bookshelf_faceFace_000 = [  0, 1, 2, 3, 4 ];
a_bookshelf_faceFace = concat(ca_bookshelf_faceFace_000);
b_bookshelf_faceFace = [cb_bookshelf_faceFace_000];
ca_bookshelf_faceSide_000 = [ [ 280.0000, 0.0000 ],[ 280.0000, 630.0000 ],[ 0.0000, 630.0000 ],[ 0.0000, 60.0000 ],[ 30.0000, 60.0000 ],[ 30.0000, 0.0000 ],[ 280.0000, 0.0000 ] ];
cb_bookshelf_faceSide_000 = [  0, 1, 2, 3, 4, 5, 6 ];
a_bookshelf_faceSide = concat(ca_bookshelf_faceSide_000);
b_bookshelf_faceSide = [cb_bookshelf_faceSide_000];
ca_bookshelf_faceSideMid_000 = [ [ 280.0000, 0.0000 ],[ 280.0000, 630.0000 ],[ 20.0000, 630.0000 ],[ 20.0000, 60.0000 ],[ 30.0000, 60.0000 ],[ 30.0000, 0.0000 ],[ 280.0000, 0.0000 ] ];
cb_bookshelf_faceSideMid_000 = [  0, 1, 2, 3, 4, 5, 6 ];
a_bookshelf_faceSideMid = concat(ca_bookshelf_faceSideMid_000);
b_bookshelf_faceSideMid = [cb_bookshelf_faceSideMid_000];
ca_bookshelf_faceTop_000 = [ [ 0.0000, 0.0000 ],[ 1200.0000, 0.0000 ],[ 1200.0000, 280.0000 ],[ 0.0000, 280.0000 ],[ 0.0000, 0.0000 ] ];
cb_bookshelf_faceTop_000 = [  0, 1, 2, 3, 4 ];
a_bookshelf_faceTop = concat(ca_bookshelf_faceTop_000);
b_bookshelf_faceTop = [cb_bookshelf_faceTop_000];
ca_bookshelf_facePlateau_000 = [ [ 20.0000, 20.0000 ],[ 590.0000, 20.0000 ],[ 590.0000, 280.0000 ],[ 20.0000, 280.0000 ],[ 20.0000, 20.0000 ] ];
cb_bookshelf_facePlateau_000 = [  0, 1, 2, 3, 4 ];
ca_bookshelf_facePlateau_001 = [ [ 610.0000, 20.0000 ],[ 1180.0000, 20.0000 ],[ 1180.0000, 280.0000 ],[ 610.0000, 280.0000 ],[ 610.0000, 20.0000 ] ];
cb_bookshelf_facePlateau_001 = [  5, 6, 7, 8, 9 ];
a_bookshelf_facePlateau = concat(ca_bookshelf_facePlateau_000, ca_bookshelf_facePlateau_001);
b_bookshelf_facePlateau = [cb_bookshelf_facePlateau_000, cb_bookshelf_facePlateau_001];
ca_bookshelf_faceBeamFace_000 = [ [ 50.0000, 70.0000 ],[ 560.0000, 70.0000 ],[ 560.0000, 100.0000 ],[ 50.0000, 100.0000 ],[ 50.0000, 70.0000 ] ];
cb_bookshelf_faceBeamFace_000 = [  0, 1, 2, 3, 4 ];
ca_bookshelf_faceBeamFace_001 = [ [ 50.0000, 430.0000 ],[ 560.0000, 430.0000 ],[ 560.0000, 460.0000 ],[ 50.0000, 460.0000 ],[ 50.0000, 430.0000 ] ];
cb_bookshelf_faceBeamFace_001 = [  5, 6, 7, 8, 9 ];
ca_bookshelf_faceBeamFace_002 = [ [ 50.0000, 600.0000 ],[ 560.0000, 600.0000 ],[ 560.0000, 630.0000 ],[ 50.0000, 630.0000 ],[ 50.0000, 600.0000 ] ];
cb_bookshelf_faceBeamFace_002 = [  10, 11, 12, 13, 14 ];
ca_bookshelf_faceBeamFace_003 = [ [ 640.0000, 70.0000 ],[ 1150.0000, 70.0000 ],[ 1150.0000, 100.0000 ],[ 640.0000, 100.0000 ],[ 640.0000, 70.0000 ] ];
cb_bookshelf_faceBeamFace_003 = [  15, 16, 17, 18, 19 ];
ca_bookshelf_faceBeamFace_004 = [ [ 640.0000, 430.0000 ],[ 1150.0000, 430.0000 ],[ 1150.0000, 460.0000 ],[ 640.0000, 460.0000 ],[ 640.0000, 430.0000 ] ];
cb_bookshelf_faceBeamFace_004 = [  20, 21, 22, 23, 24 ];
ca_bookshelf_faceBeamFace_005 = [ [ 640.0000, 600.0000 ],[ 1150.0000, 600.0000 ],[ 1150.0000, 630.0000 ],[ 640.0000, 630.0000 ],[ 640.0000, 600.0000 ] ];
cb_bookshelf_faceBeamFace_005 = [  25, 26, 27, 28, 29 ];
ca_bookshelf_faceBeamFace_006 = [ [ 20.0000, 120.0000 ],[ 50.0000, 120.0000 ],[ 50.0000, 430.0000 ],[ 20.0000, 430.0000 ],[ 20.0000, 120.0000 ] ];
cb_bookshelf_faceBeamFace_006 = [  30, 31, 32, 33, 34 ];
ca_bookshelf_faceBeamFace_007 = [ [ 20.0000, 480.0000 ],[ 50.0000, 480.0000 ],[ 50.0000, 600.0000 ],[ 20.0000, 600.0000 ],[ 20.0000, 480.0000 ] ];
cb_bookshelf_faceBeamFace_007 = [  35, 36, 37, 38, 39 ];
ca_bookshelf_faceBeamFace_008 = [ [ 1150.0000, 120.0000 ],[ 1180.0000, 120.0000 ],[ 1180.0000, 430.0000 ],[ 1150.0000, 430.0000 ],[ 1150.0000, 120.0000 ] ];
cb_bookshelf_faceBeamFace_008 = [  40, 41, 42, 43, 44 ];
ca_bookshelf_faceBeamFace_009 = [ [ 1150.0000, 480.0000 ],[ 1180.0000, 480.0000 ],[ 1180.0000, 600.0000 ],[ 1150.0000, 600.0000 ],[ 1150.0000, 480.0000 ] ];
cb_bookshelf_faceBeamFace_009 = [  45, 46, 47, 48, 49 ];
ca_bookshelf_faceBeamFace_010 = [ [ 560.0000, 120.0000 ],[ 590.0000, 120.0000 ],[ 590.0000, 430.0000 ],[ 560.0000, 430.0000 ],[ 560.0000, 120.0000 ] ];
cb_bookshelf_faceBeamFace_010 = [  50, 51, 52, 53, 54 ];
ca_bookshelf_faceBeamFace_011 = [ [ 560.0000, 480.0000 ],[ 590.0000, 480.0000 ],[ 590.0000, 600.0000 ],[ 560.0000, 600.0000 ],[ 560.0000, 480.0000 ] ];
cb_bookshelf_faceBeamFace_011 = [  55, 56, 57, 58, 59 ];
ca_bookshelf_faceBeamFace_012 = [ [ 610.0000, 120.0000 ],[ 640.0000, 120.0000 ],[ 640.0000, 430.0000 ],[ 610.0000, 430.0000 ],[ 610.0000, 120.0000 ] ];
cb_bookshelf_faceBeamFace_012 = [  60, 61, 62, 63, 64 ];
ca_bookshelf_faceBeamFace_013 = [ [ 610.0000, 480.0000 ],[ 640.0000, 480.0000 ],[ 640.0000, 600.0000 ],[ 610.0000, 600.0000 ],[ 610.0000, 480.0000 ] ];
cb_bookshelf_faceBeamFace_013 = [  65, 66, 67, 68, 69 ];
a_bookshelf_faceBeamFace = concat(ca_bookshelf_faceBeamFace_000, ca_bookshelf_faceBeamFace_001, ca_bookshelf_faceBeamFace_002, ca_bookshelf_faceBeamFace_003, ca_bookshelf_faceBeamFace_004, ca_bookshelf_faceBeamFace_005, ca_bookshelf_faceBeamFace_006, ca_bookshelf_faceBeamFace_007, ca_bookshelf_faceBeamFace_008, ca_bookshelf_faceBeamFace_009, ca_bookshelf_faceBeamFace_010, ca_bookshelf_faceBeamFace_011, ca_bookshelf_faceBeamFace_012, ca_bookshelf_faceBeamFace_013);
b_bookshelf_faceBeamFace = [cb_bookshelf_faceBeamFace_000, cb_bookshelf_faceBeamFace_001, cb_bookshelf_faceBeamFace_002, cb_bookshelf_faceBeamFace_003, cb_bookshelf_faceBeamFace_004, cb_bookshelf_faceBeamFace_005, cb_bookshelf_faceBeamFace_006, cb_bookshelf_faceBeamFace_007, cb_bookshelf_faceBeamFace_008, cb_bookshelf_faceBeamFace_009, cb_bookshelf_faceBeamFace_010, cb_bookshelf_faceBeamFace_011, cb_bookshelf_faceBeamFace_012, cb_bookshelf_faceBeamFace_013];
ca_bookshelf_faceBeamTop_000 = [ [ 20.0000, 20.0000 ],[ 50.0000, 20.0000 ],[ 50.0000, 170.0000 ],[ 20.0000, 170.0000 ],[ 20.0000, 20.0000 ] ];
cb_bookshelf_faceBeamTop_000 = [  0, 1, 2, 3, 4 ];
ca_bookshelf_faceBeamTop_001 = [ [ 1150.0000, 20.0000 ],[ 1180.0000, 20.0000 ],[ 1180.0000, 170.0000 ],[ 1150.0000, 170.0000 ],[ 1150.0000, 20.0000 ] ];
cb_bookshelf_faceBeamTop_001 = [  5, 6, 7, 8, 9 ];
ca_bookshelf_faceBeamTop_002 = [ [ 560.0000, 20.0000 ],[ 590.0000, 20.0000 ],[ 590.0000, 170.0000 ],[ 560.0000, 170.0000 ],[ 560.0000, 20.0000 ] ];
cb_bookshelf_faceBeamTop_002 = [  10, 11, 12, 13, 14 ];
ca_bookshelf_faceBeamTop_003 = [ [ 610.0000, 20.0000 ],[ 640.0000, 20.0000 ],[ 640.0000, 170.0000 ],[ 610.0000, 170.0000 ],[ 610.0000, 20.0000 ] ];
cb_bookshelf_faceBeamTop_003 = [  15, 16, 17, 18, 19 ];
a_bookshelf_faceBeamTop = concat(ca_bookshelf_faceBeamTop_000, ca_bookshelf_faceBeamTop_001, ca_bookshelf_faceBeamTop_002, ca_bookshelf_faceBeamTop_003);
b_bookshelf_faceBeamTop = [cb_bookshelf_faceBeamTop_000, cb_bookshelf_faceBeamTop_001, cb_bookshelf_faceBeamTop_002, cb_bookshelf_faceBeamTop_003];

module subpax_bookshelf_top () {
	translate( [ 0, 0, 630 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 20) polygon(a_bookshelf_faceTop, b_bookshelf_faceTop);
}

module subpax_bookshelf_plateau1 () {
	translate( [ 0, 0, 100 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 20) polygon(a_bookshelf_facePlateau, b_bookshelf_facePlateau);
}

module subpax_bookshelf_plateau2 () {
	translate( [ 0, 0, 460 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 20) polygon(a_bookshelf_facePlateau, b_bookshelf_facePlateau);
}

module subpax_bookshelf_back () {
	translate( [ 0, 20, 0 ])
		rotate( [ 90, 0, 0 ])
			   linear_extrude(height = 20) polygon(a_bookshelf_faceFace, b_bookshelf_faceFace);
}

module subpax_bookshelf_side0 () {
	translate( [ 0, 0, 0 ])
		rotate( [ 90, 0, 90 ])
			   linear_extrude(height = 20) polygon(a_bookshelf_faceSide, b_bookshelf_faceSide);
}

module subpax_bookshelf_side1 () {
	translate( [ 1180, 0, 0 ])
		rotate( [ 90, 0, 90 ])
			   linear_extrude(height = 20) polygon(a_bookshelf_faceSide, b_bookshelf_faceSide);
}

module subpax_bookshelf_sideMid () {
	translate( [ 590, 0, 0 ])
		rotate( [ 90, 0, 90 ])
			   linear_extrude(height = 20) polygon(a_bookshelf_faceSideMid, b_bookshelf_faceSideMid);
}

module subpax_bookshelf_beam1 () {
	translate( [ 0, 50, 0 ])
		rotate( [ 90, 0, 0 ])
			   linear_extrude(height = 30) polygon(a_bookshelf_faceBeamFace, b_bookshelf_faceBeamFace);
}

module subpax_bookshelf_beam20 () {
	translate( [ 0, 0, 70 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 30) polygon(a_bookshelf_faceBeamTop, b_bookshelf_faceBeamTop);
}

module subpax_bookshelf_beam21 () {
	translate( [ 0, 0, 430 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 30) polygon(a_bookshelf_faceBeamTop, b_bookshelf_faceBeamTop);
}

module subpax_bookshelf_beam22 () {
	translate( [ 0, 0, 600 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 30) polygon(a_bookshelf_faceBeamTop, b_bookshelf_faceBeamTop);
}

module pax_bookshelf () {
	union () {
		subpax_bookshelf_top();
subpax_bookshelf_plateau1();
subpax_bookshelf_plateau2();
subpax_bookshelf_back();
subpax_bookshelf_side0();
subpax_bookshelf_side1();
subpax_bookshelf_sideMid();
subpax_bookshelf_beam1();
subpax_bookshelf_beam20();
subpax_bookshelf_beam21();
subpax_bookshelf_beam22();
	}
}

pax_bookshelf();
