// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_bookshelf_faceFace_Fa000_Ctr000 = polygon({ points: [ [ 20.0000, 60.0000 ],
	[ 1180.0000, 60.0000 ],
	[ 1180.0000, 630.0000 ],
	[ 20.0000, 630.0000 ],
	[ 20.0000, 60.0000 ] ] });

face_fig_bookshelf_faceFace_Fa000 = ctr_face_fig_bookshelf_faceFace_Fa000_Ctr000;
fig_bookshelf_faceFace = face_fig_bookshelf_faceFace_Fa000;
const ctr_face_fig_bookshelf_faceSide_Fa000_Ctr000 = polygon({ points: [ [ 280.0000, 0.0000 ],
	[ 280.0000, 630.0000 ],
	[ 0.0000, 630.0000 ],
	[ 0.0000, 60.0000 ],
	[ 30.0000, 60.0000 ],
	[ 30.0000, 0.0000 ],
	[ 280.0000, 0.0000 ] ] });

face_fig_bookshelf_faceSide_Fa000 = ctr_face_fig_bookshelf_faceSide_Fa000_Ctr000;
fig_bookshelf_faceSide = face_fig_bookshelf_faceSide_Fa000;
const ctr_face_fig_bookshelf_faceSideMid_Fa000_Ctr000 = polygon({ points: [ [ 280.0000, 0.0000 ],
	[ 280.0000, 630.0000 ],
	[ 20.0000, 630.0000 ],
	[ 20.0000, 60.0000 ],
	[ 30.0000, 60.0000 ],
	[ 30.0000, 0.0000 ],
	[ 280.0000, 0.0000 ] ] });

face_fig_bookshelf_faceSideMid_Fa000 = ctr_face_fig_bookshelf_faceSideMid_Fa000_Ctr000;
fig_bookshelf_faceSideMid = face_fig_bookshelf_faceSideMid_Fa000;
const ctr_face_fig_bookshelf_faceTop_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1200.0000, 0.0000 ],
	[ 1200.0000, 280.0000 ],
	[ 0.0000, 280.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_bookshelf_faceTop_Fa000 = ctr_face_fig_bookshelf_faceTop_Fa000_Ctr000;
fig_bookshelf_faceTop = face_fig_bookshelf_faceTop_Fa000;
const ctr_face_fig_bookshelf_facePlateau_Fa000_Ctr000 = polygon({ points: [ [ 20.0000, 20.0000 ],
	[ 590.0000, 20.0000 ],
	[ 590.0000, 280.0000 ],
	[ 20.0000, 280.0000 ],
	[ 20.0000, 20.0000 ] ] });

face_fig_bookshelf_facePlateau_Fa000 = ctr_face_fig_bookshelf_facePlateau_Fa000_Ctr000;
const ctr_face_fig_bookshelf_facePlateau_Fa001_Ctr000 = polygon({ points: [ [ 610.0000, 20.0000 ],
	[ 1180.0000, 20.0000 ],
	[ 1180.0000, 280.0000 ],
	[ 610.0000, 280.0000 ],
	[ 610.0000, 20.0000 ] ] });

face_fig_bookshelf_facePlateau_Fa001 = ctr_face_fig_bookshelf_facePlateau_Fa001_Ctr000;
fig_bookshelf_facePlateau = union( face_fig_bookshelf_facePlateau_Fa000, face_fig_bookshelf_facePlateau_Fa001 );
const ctr_face_fig_bookshelf_faceBeamFace_Fa000_Ctr000 = polygon({ points: [ [ 50.0000, 70.0000 ],
	[ 560.0000, 70.0000 ],
	[ 560.0000, 100.0000 ],
	[ 50.0000, 100.0000 ],
	[ 50.0000, 70.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa000 = ctr_face_fig_bookshelf_faceBeamFace_Fa000_Ctr000;
const ctr_face_fig_bookshelf_faceBeamFace_Fa001_Ctr000 = polygon({ points: [ [ 50.0000, 430.0000 ],
	[ 560.0000, 430.0000 ],
	[ 560.0000, 460.0000 ],
	[ 50.0000, 460.0000 ],
	[ 50.0000, 430.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa001 = ctr_face_fig_bookshelf_faceBeamFace_Fa001_Ctr000;
const ctr_face_fig_bookshelf_faceBeamFace_Fa002_Ctr000 = polygon({ points: [ [ 50.0000, 600.0000 ],
	[ 560.0000, 600.0000 ],
	[ 560.0000, 630.0000 ],
	[ 50.0000, 630.0000 ],
	[ 50.0000, 600.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa002 = ctr_face_fig_bookshelf_faceBeamFace_Fa002_Ctr000;
const ctr_face_fig_bookshelf_faceBeamFace_Fa003_Ctr000 = polygon({ points: [ [ 640.0000, 70.0000 ],
	[ 1150.0000, 70.0000 ],
	[ 1150.0000, 100.0000 ],
	[ 640.0000, 100.0000 ],
	[ 640.0000, 70.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa003 = ctr_face_fig_bookshelf_faceBeamFace_Fa003_Ctr000;
const ctr_face_fig_bookshelf_faceBeamFace_Fa004_Ctr000 = polygon({ points: [ [ 640.0000, 430.0000 ],
	[ 1150.0000, 430.0000 ],
	[ 1150.0000, 460.0000 ],
	[ 640.0000, 460.0000 ],
	[ 640.0000, 430.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa004 = ctr_face_fig_bookshelf_faceBeamFace_Fa004_Ctr000;
const ctr_face_fig_bookshelf_faceBeamFace_Fa005_Ctr000 = polygon({ points: [ [ 640.0000, 600.0000 ],
	[ 1150.0000, 600.0000 ],
	[ 1150.0000, 630.0000 ],
	[ 640.0000, 630.0000 ],
	[ 640.0000, 600.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa005 = ctr_face_fig_bookshelf_faceBeamFace_Fa005_Ctr000;
const ctr_face_fig_bookshelf_faceBeamFace_Fa006_Ctr000 = polygon({ points: [ [ 20.0000, 120.0000 ],
	[ 50.0000, 120.0000 ],
	[ 50.0000, 430.0000 ],
	[ 20.0000, 430.0000 ],
	[ 20.0000, 120.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa006 = ctr_face_fig_bookshelf_faceBeamFace_Fa006_Ctr000;
const ctr_face_fig_bookshelf_faceBeamFace_Fa007_Ctr000 = polygon({ points: [ [ 20.0000, 480.0000 ],
	[ 50.0000, 480.0000 ],
	[ 50.0000, 600.0000 ],
	[ 20.0000, 600.0000 ],
	[ 20.0000, 480.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa007 = ctr_face_fig_bookshelf_faceBeamFace_Fa007_Ctr000;
const ctr_face_fig_bookshelf_faceBeamFace_Fa008_Ctr000 = polygon({ points: [ [ 1150.0000, 120.0000 ],
	[ 1180.0000, 120.0000 ],
	[ 1180.0000, 430.0000 ],
	[ 1150.0000, 430.0000 ],
	[ 1150.0000, 120.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa008 = ctr_face_fig_bookshelf_faceBeamFace_Fa008_Ctr000;
const ctr_face_fig_bookshelf_faceBeamFace_Fa009_Ctr000 = polygon({ points: [ [ 1150.0000, 480.0000 ],
	[ 1180.0000, 480.0000 ],
	[ 1180.0000, 600.0000 ],
	[ 1150.0000, 600.0000 ],
	[ 1150.0000, 480.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa009 = ctr_face_fig_bookshelf_faceBeamFace_Fa009_Ctr000;
const ctr_face_fig_bookshelf_faceBeamFace_Fa010_Ctr000 = polygon({ points: [ [ 560.0000, 120.0000 ],
	[ 590.0000, 120.0000 ],
	[ 590.0000, 430.0000 ],
	[ 560.0000, 430.0000 ],
	[ 560.0000, 120.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa010 = ctr_face_fig_bookshelf_faceBeamFace_Fa010_Ctr000;
const ctr_face_fig_bookshelf_faceBeamFace_Fa011_Ctr000 = polygon({ points: [ [ 560.0000, 480.0000 ],
	[ 590.0000, 480.0000 ],
	[ 590.0000, 600.0000 ],
	[ 560.0000, 600.0000 ],
	[ 560.0000, 480.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa011 = ctr_face_fig_bookshelf_faceBeamFace_Fa011_Ctr000;
const ctr_face_fig_bookshelf_faceBeamFace_Fa012_Ctr000 = polygon({ points: [ [ 610.0000, 120.0000 ],
	[ 640.0000, 120.0000 ],
	[ 640.0000, 430.0000 ],
	[ 610.0000, 430.0000 ],
	[ 610.0000, 120.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa012 = ctr_face_fig_bookshelf_faceBeamFace_Fa012_Ctr000;
const ctr_face_fig_bookshelf_faceBeamFace_Fa013_Ctr000 = polygon({ points: [ [ 610.0000, 480.0000 ],
	[ 640.0000, 480.0000 ],
	[ 640.0000, 600.0000 ],
	[ 610.0000, 600.0000 ],
	[ 610.0000, 480.0000 ] ] });

face_fig_bookshelf_faceBeamFace_Fa013 = ctr_face_fig_bookshelf_faceBeamFace_Fa013_Ctr000;
fig_bookshelf_faceBeamFace = union( face_fig_bookshelf_faceBeamFace_Fa000, face_fig_bookshelf_faceBeamFace_Fa001, face_fig_bookshelf_faceBeamFace_Fa002, face_fig_bookshelf_faceBeamFace_Fa003, face_fig_bookshelf_faceBeamFace_Fa004, face_fig_bookshelf_faceBeamFace_Fa005, face_fig_bookshelf_faceBeamFace_Fa006, face_fig_bookshelf_faceBeamFace_Fa007, face_fig_bookshelf_faceBeamFace_Fa008, face_fig_bookshelf_faceBeamFace_Fa009, face_fig_bookshelf_faceBeamFace_Fa010, face_fig_bookshelf_faceBeamFace_Fa011, face_fig_bookshelf_faceBeamFace_Fa012, face_fig_bookshelf_faceBeamFace_Fa013 );
const ctr_face_fig_bookshelf_faceBeamTop_Fa000_Ctr000 = polygon({ points: [ [ 20.0000, 20.0000 ],
	[ 50.0000, 20.0000 ],
	[ 50.0000, 170.0000 ],
	[ 20.0000, 170.0000 ],
	[ 20.0000, 20.0000 ] ] });

face_fig_bookshelf_faceBeamTop_Fa000 = ctr_face_fig_bookshelf_faceBeamTop_Fa000_Ctr000;
const ctr_face_fig_bookshelf_faceBeamTop_Fa001_Ctr000 = polygon({ points: [ [ 1150.0000, 20.0000 ],
	[ 1180.0000, 20.0000 ],
	[ 1180.0000, 170.0000 ],
	[ 1150.0000, 170.0000 ],
	[ 1150.0000, 20.0000 ] ] });

face_fig_bookshelf_faceBeamTop_Fa001 = ctr_face_fig_bookshelf_faceBeamTop_Fa001_Ctr000;
const ctr_face_fig_bookshelf_faceBeamTop_Fa002_Ctr000 = polygon({ points: [ [ 560.0000, 20.0000 ],
	[ 590.0000, 20.0000 ],
	[ 590.0000, 170.0000 ],
	[ 560.0000, 170.0000 ],
	[ 560.0000, 20.0000 ] ] });

face_fig_bookshelf_faceBeamTop_Fa002 = ctr_face_fig_bookshelf_faceBeamTop_Fa002_Ctr000;
const ctr_face_fig_bookshelf_faceBeamTop_Fa003_Ctr000 = polygon({ points: [ [ 610.0000, 20.0000 ],
	[ 640.0000, 20.0000 ],
	[ 640.0000, 170.0000 ],
	[ 610.0000, 170.0000 ],
	[ 610.0000, 20.0000 ] ] });

face_fig_bookshelf_faceBeamTop_Fa003 = ctr_face_fig_bookshelf_faceBeamTop_Fa003_Ctr000;
fig_bookshelf_faceBeamTop = union( face_fig_bookshelf_faceBeamTop_Fa000, face_fig_bookshelf_faceBeamTop_Fa001, face_fig_bookshelf_faceBeamTop_Fa002, face_fig_bookshelf_faceBeamTop_Fa003 );

const subpax_bookshelf_top =
	translate( [ 0, 0, 630, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 20}, fig_bookshelf_faceTop )
		)
	);


const subpax_bookshelf_plateau1 =
	translate( [ 0, 0, 100, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 20}, fig_bookshelf_facePlateau )
		)
	);


const subpax_bookshelf_plateau2 =
	translate( [ 0, 0, 460, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 20}, fig_bookshelf_facePlateau )
		)
	);


const subpax_bookshelf_back =
	translate( [ 0, 20, 0, ],
		rotate( [ 1.5707963267948966, 0, 0, ],
			   extrudeLinear( {height: 20}, fig_bookshelf_faceFace )
		)
	);


const subpax_bookshelf_side0 =
	translate( [ 0, 0, 0, ],
		rotate( [ 1.5707963267948966, 0, 1.5707963267948966, ],
			   extrudeLinear( {height: 20}, fig_bookshelf_faceSide )
		)
	);


const subpax_bookshelf_side1 =
	translate( [ 1180, 0, 0, ],
		rotate( [ 1.5707963267948966, 0, 1.5707963267948966, ],
			   extrudeLinear( {height: 20}, fig_bookshelf_faceSide )
		)
	);


const subpax_bookshelf_sideMid =
	translate( [ 590, 0, 0, ],
		rotate( [ 1.5707963267948966, 0, 1.5707963267948966, ],
			   extrudeLinear( {height: 20}, fig_bookshelf_faceSideMid )
		)
	);


const subpax_bookshelf_beam1 =
	translate( [ 0, 50, 0, ],
		rotate( [ 1.5707963267948966, 0, 0, ],
			   extrudeLinear( {height: 30}, fig_bookshelf_faceBeamFace )
		)
	);


const subpax_bookshelf_beam20 =
	translate( [ 0, 0, 70, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 30}, fig_bookshelf_faceBeamTop )
		)
	);


const subpax_bookshelf_beam21 =
	translate( [ 0, 0, 430, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 30}, fig_bookshelf_faceBeamTop )
		)
	);


const subpax_bookshelf_beam22 =
	translate( [ 0, 0, 600, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 30}, fig_bookshelf_faceBeamTop )
		)
	);

const pax_bookshelf = union( subpax_bookshelf_top, subpax_bookshelf_plateau1, subpax_bookshelf_plateau2, subpax_bookshelf_back, subpax_bookshelf_side0, subpax_bookshelf_side1, subpax_bookshelf_sideMid, subpax_bookshelf_beam1, subpax_bookshelf_beam20, subpax_bookshelf_beam21, subpax_bookshelf_beam22 );

return pax_bookshelf;
}
module.exports = { main };
